// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV-fQ3x60KieyYqHpzh1s2-6PytM1PvWw',
    appId: '1:1022939951262:web:8370f3390349668e23cb8f',
    messagingSenderId: '1022939951262',
    projectId: 'lost-and-found-campus-a4af7',
    authDomain: 'lost-and-found-campus-a4af7.firebaseapp.com',
    storageBucket: 'lost-and-found-campus-a4af7.firebasestorage.app',
    measurementId: 'G-3BY7JEQPP7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA6g7-CnHpBdIDSYXzdk8I5o-CazaOilU',
    appId: '1:1022939951262:android:42a302633797120d23cb8f',
    messagingSenderId: '1022939951262',
    projectId: 'lost-and-found-campus-a4af7',
    storageBucket: 'lost-and-found-campus-a4af7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuUQtkiTcFhuJ2y1E4wDWoDxB0JyZ_Ej0',
    appId: '1:1022939951262:ios:f7c422774418bd6323cb8f',
    messagingSenderId: '1022939951262',
    projectId: 'lost-and-found-campus-a4af7',
    storageBucket: 'lost-and-found-campus-a4af7.firebasestorage.app',
    iosBundleId: 'com.example.lostFoundCampus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuUQtkiTcFhuJ2y1E4wDWoDxB0JyZ_Ej0',
    appId: '1:1022939951262:ios:f7c422774418bd6323cb8f',
    messagingSenderId: '1022939951262',
    projectId: 'lost-and-found-campus-a4af7',
    storageBucket: 'lost-and-found-campus-a4af7.firebasestorage.app',
    iosBundleId: 'com.example.lostFoundCampus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCV-fQ3x60KieyYqHpzh1s2-6PytM1PvWw',
    appId: '1:1022939951262:web:f1f242f3b351b01523cb8f',
    messagingSenderId: '1022939951262',
    projectId: 'lost-and-found-campus-a4af7',
    authDomain: 'lost-and-found-campus-a4af7.firebaseapp.com',
    storageBucket: 'lost-and-found-campus-a4af7.firebasestorage.app',
    measurementId: 'G-20ZLEQLZ8G',
  );
}
