// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZgTZCYO7CMyFFvLNAli2pPBMaQNOXSJo',
    appId: '1:788527914731:web:2761dca3f52c8f5cc4e8ae',
    messagingSenderId: '788527914731',
    projectId: 'fb-auth-1755',
    authDomain: 'fb-auth-1755.firebaseapp.com',
    storageBucket: 'fb-auth-1755.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEM4tuooNt3uN2TmUBU5rMSiW50kg5oFQ',
    appId: '1:788527914731:android:fa0cb6d96dae8111c4e8ae',
    messagingSenderId: '788527914731',
    projectId: 'fb-auth-1755',
    storageBucket: 'fb-auth-1755.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPQoN34ErruiDOO1sDJo9cnbZs8yEabQs',
    appId: '1:788527914731:ios:ce2e129445cdca7fc4e8ae',
    messagingSenderId: '788527914731',
    projectId: 'fb-auth-1755',
    storageBucket: 'fb-auth-1755.firebasestorage.app',
    iosClientId: '788527914731-srni68r226n49k19pip6odap5ipp1igc.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPQoN34ErruiDOO1sDJo9cnbZs8yEabQs',
    appId: '1:788527914731:ios:ce2e129445cdca7fc4e8ae',
    messagingSenderId: '788527914731',
    projectId: 'fb-auth-1755',
    storageBucket: 'fb-auth-1755.firebasestorage.app',
    iosClientId: '788527914731-srni68r226n49k19pip6odap5ipp1igc.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZgTZCYO7CMyFFvLNAli2pPBMaQNOXSJo',
    appId: '1:788527914731:web:2a804c8b51ceff8ec4e8ae',
    messagingSenderId: '788527914731',
    projectId: 'fb-auth-1755',
    authDomain: 'fb-auth-1755.firebaseapp.com',
    storageBucket: 'fb-auth-1755.firebasestorage.app',
  );

}