// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWFc8g4b8G8sCQDcRxcceoIPH2t-5XeSs',
    appId: '1:484627551111:web:a26bb6f1cfef7e23d2f922',
    messagingSenderId: '484627551111',
    projectId: 'fir-auth-class-demo',
    authDomain: 'fir-auth-class-demo.firebaseapp.com',
    storageBucket: 'fir-auth-class-demo.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOf8Cv-hR8Kqv_rQW1zkanNFwDV1tSliY',
    appId: '1:484627551111:android:1b9a788493eeb8bed2f922',
    messagingSenderId: '484627551111',
    projectId: 'fir-auth-class-demo',
    storageBucket: 'fir-auth-class-demo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEORjBrWuP8DO6FzrlA8QQTvE3NswhiSw',
    appId: '1:484627551111:ios:37721621dc05fcf8d2f922',
    messagingSenderId: '484627551111',
    projectId: 'fir-auth-class-demo',
    storageBucket: 'fir-auth-class-demo.firebasestorage.app',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEORjBrWuP8DO6FzrlA8QQTvE3NswhiSw',
    appId: '1:484627551111:ios:37721621dc05fcf8d2f922',
    messagingSenderId: '484627551111',
    projectId: 'fir-auth-class-demo',
    storageBucket: 'fir-auth-class-demo.firebasestorage.app',
    iosBundleId: 'com.example.firebaseDemo',
  );
}
