// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSo8DtletzWqmvATTPskMB8v16DdWNb0o',
    appId: '1:331676840810:web:f9a067cba3feef4c7d2b13',
    messagingSenderId: '331676840810',
    projectId: 'fir-auth-1746-92fcd',
    authDomain: 'fir-auth-1746-92fcd.firebaseapp.com',
    storageBucket: 'fir-auth-1746-92fcd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXrtC95AndO4snM9eus09M24GkJjV4A-s',
    appId: '1:331676840810:android:54229b76e047391b7d2b13',
    messagingSenderId: '331676840810',
    projectId: 'fir-auth-1746-92fcd',
    storageBucket: 'fir-auth-1746-92fcd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaUuC_ajidMnASNSg17NJrDQpeQXO6tw0',
    appId: '1:331676840810:ios:d212adf0578463c37d2b13',
    messagingSenderId: '331676840810',
    projectId: 'fir-auth-1746-92fcd',
    storageBucket: 'fir-auth-1746-92fcd.firebasestorage.app',
    iosClientId: '331676840810-srdikhabhpd03ftujmgntuqhl821np68.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuth1746',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaUuC_ajidMnASNSg17NJrDQpeQXO6tw0',
    appId: '1:331676840810:ios:d212adf0578463c37d2b13',
    messagingSenderId: '331676840810',
    projectId: 'fir-auth-1746-92fcd',
    storageBucket: 'fir-auth-1746-92fcd.firebasestorage.app',
    iosClientId: '331676840810-srdikhabhpd03ftujmgntuqhl821np68.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuth1746',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSo8DtletzWqmvATTPskMB8v16DdWNb0o',
    appId: '1:331676840810:web:2e4d2a23b7011e487d2b13',
    messagingSenderId: '331676840810',
    projectId: 'fir-auth-1746-92fcd',
    authDomain: 'fir-auth-1746-92fcd.firebaseapp.com',
    storageBucket: 'fir-auth-1746-92fcd.firebasestorage.app',
  );

}