// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1cmvIEHe0UoQARUY_26YkzQkbta8N-TA',
    appId: '1:972755380800:android:45272fc3097f2db7a68da5',
    messagingSenderId: '972755380800',
    projectId: 'fir-demo-project-244b3',
    storageBucket: 'fir-demo-project-244b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqfi1T0m7VDJJ8jfG-03j2RP4d7BRd7vA',
    appId: '1:972755380800:ios:b850347da133e635a68da5',
    messagingSenderId: '972755380800',
    projectId: 'fir-demo-project-244b3',
    storageBucket: 'fir-demo-project-244b3.firebasestorage.app',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqFNHdqvx1u5RgyagAvsFWHWCzlnG3HTc',
    appId: '1:972755380800:web:b19c375884eb4a69a68da5',
    messagingSenderId: '972755380800',
    projectId: 'fir-demo-project-244b3',
    authDomain: 'fir-demo-project-244b3.firebaseapp.com',
    storageBucket: 'fir-demo-project-244b3.firebasestorage.app',
    measurementId: 'G-T4EGD5H7GK',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqFNHdqvx1u5RgyagAvsFWHWCzlnG3HTc',
    appId: '1:972755380800:web:a37f7523818d4fe8a68da5',
    messagingSenderId: '972755380800',
    projectId: 'fir-demo-project-244b3',
    authDomain: 'fir-demo-project-244b3.firebaseapp.com',
    storageBucket: 'fir-demo-project-244b3.firebasestorage.app',
    measurementId: 'G-XXNXSDMZBC',
  );

}